baseURL = 'https://kylejones200.github.io/our_table/'
languageCode = 'en-us'
title = 'Our Table - Recipe Collection'

# GitHub Pages configuration
relativeURLs = false
canonifyURLs = true

# Content configuration
[pagination]
  pagerSize = 10
  path = 'page'

# Markup configuration
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Params
[params]
  description = 'A collection of family recipes'
  author = 'Kyle Jones'

# Taxonomies
[taxonomies]
  tag = "tags"
  cuisine = "cuisines"
  course = "courses"
  diet = "diets"

# Permalinks
[permalinks]
  recipes = "/recipes/:slug/"

# URL configuration
[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  lastmod = [":git", "lastmod", "date", "publishDate"]
  publishDate = ["publishDate", "date"]
  expiryDate = ["expiryDate"]

# Build configuration
[build]
  writeStats = true
